; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp01_1m]
; configuration for ESP-01 with 1MB flash
; only DotMatrix display is possible with this board due to limited gpio
platform = espressif8266
board = esp01_1m
framework = arduino

upload_protocol = espota
upload_port = 192.168.1.21

upload_flags =
    --auth=admin

board_build.filesystem = littlefs

; Allocate 64KB to the filesystem, leaving 960KB for the program & OTA
board_build.ldscript = eagle.flash.1m64.ld

lib_deps =
    ; Display Libraries
    majicdesigns/MD_Parola @ ^3.7.1
    majicdesigns/MD_MAX72XX @ ^3.5.0
    
    ; Time and NTP
    arduino-libraries/NTPClient @ ^3.2.1
    paulstoffregen/Time @ ^1.6.1
    
    ; Data Parsing
    bblanchon/ArduinoJson @ ^7.0.4
    
    ; Async Web Server
    ESP32Async/ESPAsyncTCP @ ^2.0.0
    ESP32Async/ESPAsyncWebServer @ ^3.10.3